export interface AnimationPreset {
  id: string;
  name: string;
  description: string;
  cssKeyframes: string;
  animationCSS: string;
  category: 'movement' | 'scare' | 'atmospheric' | 'visual';
  icon: string;
}

export const ANIMATION_PRESETS: AnimationPreset[] = [
  // ===== MOVEMENT =====
  { id: 'float', name: 'Ghostly Float', description: 'Eerie floating spirit motion', cssKeyframes: '', animationCSS: 'animation: ha-float 4s ease-in-out infinite', category: 'movement', icon: '👻' },
  { id: 'shake', name: 'Demonic Shake', description: 'Intense possession shaking', cssKeyframes: '', animationCSS: 'animation: ha-shake 0.3s ease-in-out infinite', category: 'movement', icon: '😈' },
  { id: 'creep', name: 'Creeping Shadow', description: 'Slow pan across screen', cssKeyframes: '', animationCSS: 'animation: ha-creep 6s ease-in-out infinite', category: 'movement', icon: '🕷️' },
  { id: 'swing', name: 'Pendulum Swing', description: 'Hanging pendulum sway', cssKeyframes: '', animationCSS: 'animation: ha-swing 2.5s ease-in-out infinite', category: 'movement', icon: '⚖️' },
  { id: 'drift-left', name: 'Drift Left', description: 'Slow drift to the left', cssKeyframes: '', animationCSS: 'animation: ha-drift-left 3s ease-in-out infinite', category: 'movement', icon: '←' },
  { id: 'drift-right', name: 'Drift Right', description: 'Slow drift to the right', cssKeyframes: '', animationCSS: 'animation: ha-drift-right 3s ease-in-out infinite', category: 'movement', icon: '→' },
  { id: 'spiral', name: 'Death Spiral', description: 'Spiraling rotation motion', cssKeyframes: '', animationCSS: 'animation: ha-spiral 3s linear infinite', category: 'movement', icon: '🌀' },
  { id: 'sway', name: 'Corpse Sway', description: 'Slow swaying like a hanging body', cssKeyframes: '', animationCSS: 'animation: ha-sway 3s ease-in-out infinite', category: 'movement', icon: '🪢' },
  { id: 'bounce', name: 'Demon Bounce', description: 'Erratic bouncing movement', cssKeyframes: '', animationCSS: 'animation: ha-bounce 1.5s cubic-bezier(0.36, 0.07, 0.19, 0.97) infinite', category: 'movement', icon: '🎃' },
  { id: 'teleport', name: 'Shadow Teleport', description: 'Blinks in and out of position', cssKeyframes: '', animationCSS: 'animation: ha-teleport 2s step-start infinite', category: 'movement', icon: '⚡' },
  { id: 'slide-down', name: 'Descend from Void', description: 'Slides down from top', cssKeyframes: '', animationCSS: 'animation: ha-slide-down 4s ease-in-out infinite', category: 'movement', icon: '⬇️' },
  { id: 'slide-up', name: 'Rise from Below', description: 'Rises up from below', cssKeyframes: '', animationCSS: 'animation: ha-slide-up 4s ease-in-out infinite', category: 'movement', icon: '⬆️' },
  { id: 'zigzag', name: 'Possessed Zigzag', description: 'Chaotic zigzag movement', cssKeyframes: '', animationCSS: 'animation: ha-zigzag 2s linear infinite', category: 'movement', icon: '⚡' },
  { id: 'earthquake', name: 'Earthquake Terror', description: 'Massive violent shaking', cssKeyframes: '', animationCSS: 'animation: ha-earthquake 0.1s ease-in-out infinite', category: 'movement', icon: '🌋' },
  { id: 'levitate-spin', name: 'Levitate & Spin', description: 'Floats while slowly spinning', cssKeyframes: '', animationCSS: 'animation: ha-levitate-spin 5s ease-in-out infinite', category: 'movement', icon: '🔄' },
  { id: 'marionette', name: 'Marionette Drop', description: 'Jerky puppet-like dropping', cssKeyframes: '', animationCSS: 'animation: ha-marionette 1.5s ease-in-out infinite', category: 'movement', icon: '🎭' },
  { id: 'crawl', name: 'Crawl Across', description: 'Low crawling motion', cssKeyframes: '', animationCSS: 'animation: ha-crawl 5s ease-in-out infinite', category: 'movement', icon: '🦟' },
  { id: 'jerk', name: 'Possession Jerk', description: 'Violent sudden jerking', cssKeyframes: '', animationCSS: 'animation: ha-jerk 0.8s ease-in-out infinite', category: 'movement', icon: '💀' },
  { id: 'orbit', name: 'Dark Orbit', description: 'Orbits around center point', cssKeyframes: '', animationCSS: 'animation: ha-orbit 4s linear infinite', category: 'movement', icon: '🌙' },
  { id: 'tidal', name: 'Tidal Wave', description: 'Sweeping wave motion', cssKeyframes: '', animationCSS: 'animation: ha-tidal 3s ease-in-out infinite', category: 'movement', icon: '🌊' },
  { id: 'chaotic', name: 'Chaotic Dance', description: 'Completely random chaotic motion', cssKeyframes: '', animationCSS: 'animation: ha-chaotic 0.5s linear infinite', category: 'movement', icon: '🔥' },
  { id: 'rise-fall', name: 'Rise and Fall', description: 'Smooth up and down cycle', cssKeyframes: '', animationCSS: 'animation: ha-rise-fall 3s ease-in-out infinite', category: 'movement', icon: '📈' },
  { id: 'sidewind', name: 'Sidewinder', description: 'Side to side slithering', cssKeyframes: '', animationCSS: 'animation: ha-sidewind 2s ease-in-out infinite', category: 'movement', icon: '🐍' },
  { id: 'pulse-move', name: 'Pulse & Move', description: 'Pulses while drifting', cssKeyframes: '', animationCSS: 'animation: ha-pulse-move 3s ease-in-out infinite', category: 'movement', icon: '💓' },
  { id: 'warp-drift', name: 'Warp Drift', description: 'Warping spatial drift', cssKeyframes: '', animationCSS: 'animation: ha-warp-drift 4s ease-in-out infinite', category: 'movement', icon: '🌌' },

  // ===== SCARE =====
  { id: 'jumpscare', name: 'Jump Scare', description: 'Sudden explosive zoom burst', cssKeyframes: '', animationCSS: 'animation: ha-jumpscare 3s ease-in-out infinite', category: 'scare', icon: '😱' },
  { id: 'flash-blink', name: 'Flash Blink', description: 'Rapid white flash strobe', cssKeyframes: '', animationCSS: 'animation: ha-flash-blink 0.5s step-start infinite', category: 'scare', icon: '⚡' },
  { id: 'sudden-loom', name: 'Sudden Loom', description: 'Grows suddenly huge then recoils', cssKeyframes: '', animationCSS: 'animation: ha-sudden-loom 2s ease-in-out infinite', category: 'scare', icon: '😰' },
  { id: 'evil-zoom', name: 'Evil Zoom In', description: 'Relentlessly zooms closer', cssKeyframes: '', animationCSS: 'animation: ha-evil-zoom 4s ease-in infinite', category: 'scare', icon: '🔍' },
  { id: 'strobe', name: 'Terror Strobe', description: 'Rapid full strobe flash', cssKeyframes: '', animationCSS: 'animation: ha-strobe 0.15s step-start infinite', category: 'scare', icon: '🔆' },
  { id: 'blackout-reveal', name: 'Blackout Reveal', description: 'Hides then suddenly appears', cssKeyframes: '', animationCSS: 'animation: ha-blackout-reveal 3s ease-in-out infinite', category: 'scare', icon: '🌑' },
  { id: 'rapid-approach', name: 'Rapid Approach', description: 'Rushes toward viewer fast', cssKeyframes: '', animationCSS: 'animation: ha-rapid-approach 2s ease-out infinite', category: 'scare', icon: '💨' },
  { id: 'mirror-flip', name: 'Mirror Flip Scare', description: 'Flips horizontally with flash', cssKeyframes: '', animationCSS: 'animation: ha-mirror-flip 2s ease-in-out infinite', category: 'scare', icon: '🪞' },
  { id: 'warp-jump', name: 'Warp Jump', description: 'Teleport warp with distortion', cssKeyframes: '', animationCSS: 'animation: ha-warp-jump 2.5s ease-in-out infinite', category: 'scare', icon: '🌀' },
  { id: 'crash-in', name: 'Crash In', description: 'Slams in from outside frame', cssKeyframes: '', animationCSS: 'animation: ha-crash-in 2s ease-out infinite', category: 'scare', icon: '💥' },
  { id: 'slam-down', name: 'Slam Down', description: 'Drops with violent impact', cssKeyframes: '', animationCSS: 'animation: ha-slam-down 2s ease-in-out infinite', category: 'scare', icon: '⬇️' },
  { id: 'eye-open', name: 'Eye Open', description: 'Appears like a blinking eye', cssKeyframes: '', animationCSS: 'animation: ha-eye-open 3s ease-in-out infinite', category: 'scare', icon: '👁️' },
  { id: 'death-drop', name: 'Death Drop', description: 'Falls and disappears below', cssKeyframes: '', animationCSS: 'animation: ha-death-drop 2.5s ease-in infinite', category: 'scare', icon: '💀' },
  { id: 'nuclear-pulse', name: 'Nuclear Pulse', description: 'Explosive radial blast pulse', cssKeyframes: '', animationCSS: 'animation: ha-nuclear-pulse 1.5s ease-out infinite', category: 'scare', icon: '☢️' },
  { id: 'distort-warp', name: 'Distort Warp', description: 'Reality-warping distortion', cssKeyframes: '', animationCSS: 'animation: ha-distort-warp 3s ease-in-out infinite', category: 'scare', icon: '🌪️' },
  { id: 'horror-snap', name: 'Horror Snap', description: 'Snaps violently in random directions', cssKeyframes: '', animationCSS: 'animation: ha-horror-snap 0.4s step-start infinite', category: 'scare', icon: '👿' },
  { id: 'rage-flash', name: 'Rage Flash', description: 'Red rage flash strobing', cssKeyframes: '', animationCSS: 'animation: ha-rage-flash 0.3s step-start infinite', category: 'scare', icon: '😡' },
  { id: 'final-reveal', name: 'Final Reveal', description: 'Slowly reveals from darkness', cssKeyframes: '', animationCSS: 'animation: ha-final-reveal 4s ease-in-out infinite', category: 'scare', icon: '🔦' },
  { id: 'dive-bomb', name: 'Dive Bomb', description: 'Dives from above at speed', cssKeyframes: '', animationCSS: 'animation: ha-dive-bomb 2s ease-in infinite', category: 'scare', icon: '💫' },
  { id: 'possession', name: 'Possession Burst', description: 'Chaotic possessed explosion', cssKeyframes: '', animationCSS: 'animation: ha-possession 0.5s ease-in-out infinite', category: 'scare', icon: '👾' },
  { id: 'rage-burst', name: 'Rage Burst', description: 'Explodes outward in rage', cssKeyframes: '', animationCSS: 'animation: ha-rage-burst 1s ease-out infinite', category: 'scare', icon: '💢' },
  { id: 'terror-vibrate', name: 'Terror Vibrate', description: 'High-frequency terror vibration', cssKeyframes: '', animationCSS: 'animation: ha-terror-vibrate 0.05s linear infinite', category: 'scare', icon: '📳' },
  { id: 'appear-ghost', name: 'Ghost Appear', description: 'Materializes from nothing', cssKeyframes: '', animationCSS: 'animation: ha-appear-ghost 2.5s ease-in-out infinite', category: 'scare', icon: '👻' },
  { id: 'grab-reach', name: 'Grab & Reach', description: 'Reaches out to grab viewer', cssKeyframes: '', animationCSS: 'animation: ha-grab-reach 2s ease-in-out infinite', category: 'scare', icon: '✋' },
  { id: 'shatter', name: 'Reality Shatter', description: 'Shatters into fragments', cssKeyframes: '', animationCSS: 'animation: ha-shatter 2s ease-in-out infinite', category: 'scare', icon: '💔' },

  // ===== ATMOSPHERIC =====
  { id: 'haunting', name: 'Haunting Fade', description: 'Ghostly appear/disappear with blur', cssKeyframes: '', animationCSS: 'animation: ha-haunting 6s ease-in-out infinite', category: 'atmospheric', icon: '🌫️' },
  { id: 'pulse-glow', name: 'Blood Pulse Glow', description: 'Pulsing red glow heartbeat', cssKeyframes: '', animationCSS: 'animation: ha-pulse-glow 2s ease-in-out infinite', category: 'atmospheric', icon: '❤️' },
  { id: 'flicker', name: 'Light Flicker', description: 'Dying light flickering', cssKeyframes: '', animationCSS: 'animation: ha-flicker 3s ease-in-out infinite', category: 'atmospheric', icon: '🕯️' },
  { id: 'shadow-breathe', name: 'Shadow Breathe', description: 'Slow dark breathing presence', cssKeyframes: '', animationCSS: 'animation: ha-shadow-breathe 4s ease-in-out infinite', category: 'atmospheric', icon: '🫁' },
  { id: 'fog-roll', name: 'Fog Roll', description: 'Rolling fog wisps', cssKeyframes: '', animationCSS: 'animation: ha-fog-roll 8s ease-in-out infinite', category: 'atmospheric', icon: '🌁' },
  { id: 'spectral-shift', name: 'Spectral Shift', description: 'Shifts between spectral states', cssKeyframes: '', animationCSS: 'animation: ha-spectral-shift 5s ease-in-out infinite', category: 'atmospheric', icon: '🌈' },
  { id: 'nightmare-phase', name: 'Nightmare Phase', description: 'Phases in and out of reality', cssKeyframes: '', animationCSS: 'animation: ha-nightmare-phase 6s ease-in-out infinite', category: 'atmospheric', icon: '😴' },
  { id: 'dark-ritual', name: 'Dark Ritual', description: 'Pulsing dark energy', cssKeyframes: '', animationCSS: 'animation: ha-dark-ritual 3s ease-in-out infinite', category: 'atmospheric', icon: '🔮' },
  { id: 'spirit-manifest', name: 'Spirit Manifest', description: 'Spirit slowly materializes', cssKeyframes: '', animationCSS: 'animation: ha-spirit-manifest 8s ease-in-out infinite', category: 'atmospheric', icon: '✨' },
  { id: 'aura-glow', name: 'Cursed Aura', description: 'Cursed glowing aura pulse', cssKeyframes: '', animationCSS: 'animation: ha-aura-glow 3s ease-in-out infinite', category: 'atmospheric', icon: '🌟' },
  { id: 'infernal-glow', name: 'Infernal Glow', description: 'Hellish orange-red glow', cssKeyframes: '', animationCSS: 'animation: ha-infernal-glow 2.5s ease-in-out infinite', category: 'atmospheric', icon: '🔥' },
  { id: 'grave-rise', name: 'Grave Rise', description: 'Rises from the grave mist', cssKeyframes: '', animationCSS: 'animation: ha-grave-rise 5s ease-out infinite', category: 'atmospheric', icon: '⚰️' },
  { id: 'moonlit-wail', name: 'Moonlit Wail', description: 'Wailing under the moon', cssKeyframes: '', animationCSS: 'animation: ha-moonlit-wail 6s ease-in-out infinite', category: 'atmospheric', icon: '🌕' },
  { id: 'astral-drain', name: 'Astral Drain', description: 'Life draining away slowly', cssKeyframes: '', animationCSS: 'animation: ha-astral-drain 4s ease-in-out infinite', category: 'atmospheric', icon: '🌀' },
  { id: 'limbo-float', name: 'Limbo Float', description: 'Floating between worlds', cssKeyframes: '', animationCSS: 'animation: ha-limbo-float 7s ease-in-out infinite', category: 'atmospheric', icon: '🕊️' },
  { id: 'sigil-burn', name: 'Sigil Burn', description: 'Burning sigil glow effect', cssKeyframes: '', animationCSS: 'animation: ha-sigil-burn 4s ease-in-out infinite', category: 'atmospheric', icon: '🔯' },
  { id: 'death-breath', name: 'Death Breath', description: 'Cold death breath mist', cssKeyframes: '', animationCSS: 'animation: ha-death-breath 5s ease-in-out infinite', category: 'atmospheric', icon: '💨' },
  { id: 'void-portal', name: 'Void Portal', description: 'Opening portal to the void', cssKeyframes: '', animationCSS: 'animation: ha-void-portal 6s ease-in-out infinite', category: 'atmospheric', icon: '🌑' },
  { id: 'purgatory', name: 'Purgatory Pulse', description: 'Purgatory dimension pulse', cssKeyframes: '', animationCSS: 'animation: ha-purgatory 4s ease-in-out infinite', category: 'atmospheric', icon: '☁️' },
  { id: 'underworld', name: 'Underworld Glow', description: 'Glowing from the underworld', cssKeyframes: '', animationCSS: 'animation: ha-underworld 3s ease-in-out infinite', category: 'atmospheric', icon: '⛓️' },
  { id: 'eternal-dark', name: 'Eternal Darkness', description: 'Swallowed by eternal dark', cssKeyframes: '', animationCSS: 'animation: ha-eternal-dark 8s ease-in-out infinite', category: 'atmospheric', icon: '🌚' },
  { id: 'terror-fog', name: 'Terror Fog', description: 'Dense terror fog swirl', cssKeyframes: '', animationCSS: 'animation: ha-terror-fog 10s ease-in-out infinite', category: 'atmospheric', icon: '🌫️' },
  { id: 'cursed-halo', name: 'Cursed Halo', description: 'Dark cursed halo above head', cssKeyframes: '', animationCSS: 'animation: ha-cursed-halo 3s linear infinite', category: 'atmospheric', icon: '👼' },
  { id: 'soul-emerge', name: 'Soul Emerge', description: 'Soul emerging from body', cssKeyframes: '', animationCSS: 'animation: ha-soul-emerge 6s ease-in-out infinite', category: 'atmospheric', icon: '💫' },
  { id: 'ghost-drift', name: 'Ghost Drift Through', description: 'Ghost drifts through walls', cssKeyframes: '', animationCSS: 'animation: ha-ghost-drift 8s ease-in-out infinite', category: 'atmospheric', icon: '🏚️' },

  // ===== VISUAL EFFECTS =====
  { id: 'glitch', name: 'Glitch Horror', description: 'Digital glitch with color split', cssKeyframes: '', animationCSS: 'animation: ha-glitch 4s ease-in-out infinite', category: 'visual', icon: '📺' },
  { id: 'blood-filter', name: 'Blood Filter', description: 'Deep blood red color wash', cssKeyframes: '', animationCSS: 'animation: ha-blood-filter 3s ease-in-out infinite', category: 'visual', icon: '🩸' },
  { id: 'chromatic', name: 'Chromatic Aberration', description: 'RGB color split distortion', cssKeyframes: '', animationCSS: 'animation: ha-chromatic 2s ease-in-out infinite', category: 'visual', icon: '🎨' },
  { id: 'tv-static', name: 'TV Static Corrupt', description: 'Television static corruption', cssKeyframes: '', animationCSS: 'animation: ha-tv-static 0.1s step-start infinite', category: 'visual', icon: '📡' },
  { id: 'heat-distort', name: 'Hell Heat Distort', description: 'Hell heat wave distortion', cssKeyframes: '', animationCSS: 'animation: ha-heat-distort 2s ease-in-out infinite', category: 'visual', icon: '🌡️' },
  { id: 'shadow-clone', name: 'Shadow Clone', description: 'Creates dark shadow copies', cssKeyframes: '', animationCSS: 'animation: ha-shadow-clone 3s ease-in-out infinite', category: 'visual', icon: '👥' },
  { id: 'corruption', name: 'Digital Corruption', description: 'Digital pixel corruption', cssKeyframes: '', animationCSS: 'animation: ha-corruption 0.5s step-start infinite', category: 'visual', icon: '💾' },
  { id: 'acid-burn', name: 'Acid Burn', description: 'Acid melting visual effect', cssKeyframes: '', animationCSS: 'animation: ha-acid-burn 4s ease-in-out infinite', category: 'visual', icon: '☣️' },
  { id: 'toxic-glow', name: 'Toxic Glow', description: 'Toxic green glowing pulse', cssKeyframes: '', animationCSS: 'animation: ha-toxic-glow 2.5s ease-in-out infinite', category: 'visual', icon: '🧪' },
  { id: 'possession-pulse', name: 'Possession Pulse', description: 'Demonic possession visual pulse', cssKeyframes: '', animationCSS: 'animation: ha-possession-pulse 1.5s ease-in-out infinite', category: 'visual', icon: '👿' },
  { id: 'cursed-invert', name: 'Cursed Invert', description: 'Color inversion curse', cssKeyframes: '', animationCSS: 'animation: ha-cursed-invert 2s step-start infinite', category: 'visual', icon: '🔄' },
  { id: 'hellfire-tint', name: 'Hellfire Tint', description: 'Orange hellfire color tint', cssKeyframes: '', animationCSS: 'animation: ha-hellfire-tint 3s ease-in-out infinite', category: 'visual', icon: '🔥' },
  { id: 'pixel-corrupt', name: 'Pixel Corrupt', description: 'Pixelation corruption glitch', cssKeyframes: '', animationCSS: 'animation: ha-pixel-corrupt 0.3s step-start infinite', category: 'visual', icon: '🖥️' },
  { id: 'void-tear', name: 'Void Tear', description: 'Tears in reality void', cssKeyframes: '', animationCSS: 'animation: ha-void-tear 3s ease-in-out infinite', category: 'visual', icon: '🌌' },
  { id: 'soul-drain', name: 'Soul Drain', description: 'Life color draining away', cssKeyframes: '', animationCSS: 'animation: ha-soul-drain 4s ease-in-out infinite', category: 'visual', icon: '💔' },
  { id: 'blood-moon', name: 'Blood Moon Filter', description: 'Blood moon red sky filter', cssKeyframes: '', animationCSS: 'animation: ha-blood-moon 5s ease-in-out infinite', category: 'visual', icon: '🌕' },
  { id: 'spectral-echo', name: 'Spectral Echo', description: 'Ghost trail echo effect', cssKeyframes: '', animationCSS: 'animation: ha-spectral-echo 2s ease-in-out infinite', category: 'visual', icon: '👁️' },
  { id: 'demon-vision', name: 'Demon Vision', description: 'Seeing through demon eyes', cssKeyframes: '', animationCSS: 'animation: ha-demon-vision 4s ease-in-out infinite', category: 'visual', icon: '👁' },
  { id: 'nightmare-overlay', name: 'Nightmare Overlay', description: 'Nightmare dream overlay', cssKeyframes: '', animationCSS: 'animation: ha-nightmare-overlay 6s ease-in-out infinite', category: 'visual', icon: '🌙' },
  { id: 'laser-eyes', name: 'Laser Eyes Glow', description: 'Glowing laser beam eyes', cssKeyframes: '', animationCSS: 'animation: ha-laser-eyes 1.5s ease-in-out infinite', category: 'visual', icon: '🔴' },
  { id: 'film-grain', name: 'Horror Film Grain', description: 'Old horror movie grain', cssKeyframes: '', animationCSS: 'animation: ha-film-grain 0.1s step-start infinite', category: 'visual', icon: '🎞️' },
  { id: 'mirror-world', name: 'Mirror World Flip', description: 'Flips into mirror dimension', cssKeyframes: '', animationCSS: 'animation: ha-mirror-world 3s step-start infinite', category: 'visual', icon: '🪞' },
  { id: 'hell-warp', name: 'Hell Warp', description: 'Reality warps to hellscape', cssKeyframes: '', animationCSS: 'animation: ha-hell-warp 4s ease-in-out infinite', category: 'visual', icon: '🌋' },
  { id: 'celestial-horror', name: 'Celestial Horror', description: 'Cosmic horror from above', cssKeyframes: '', animationCSS: 'animation: ha-celestial-horror 8s ease-in-out infinite', category: 'visual', icon: '🌠' },
  { id: 'blood-splat', name: 'Blood Splatter', description: 'Blood splatter pulse effect', cssKeyframes: '', animationCSS: 'animation: ha-blood-splat 2s ease-out infinite', category: 'visual', icon: '🩸' },
];

export const ASPECT_RATIOS = [
  { id: '16:9-1080', label: '1920×1080 — Full HD (Standard)', width: 1920, height: 1080, tag: 'Standard' },
  { id: '16:9-1440', label: '2560×1440 — 2K QHD', width: 2560, height: 1440, tag: '2K' },
  { id: '16:9-4k', label: '3840×2160 — 4K UHD', width: 3840, height: 2160, tag: '4K' },
  { id: '16:9-720', label: '1280×720 — HD 720p', width: 1280, height: 720, tag: 'HD' },
  { id: 'twitch', label: '1920×1080 — Twitch Standard', width: 1920, height: 1080, tag: 'Twitch' },
  { id: 'obs-canvas', label: '1920×1080 — OBS Canvas', width: 1920, height: 1080, tag: 'OBS' },
  { id: 'obs-4k', label: '3840×2160 — OBS 4K Canvas', width: 3840, height: 2160, tag: 'OBS 4K' },
  { id: 'tiktok', label: '1080×1920 — TikTok Vertical', width: 1080, height: 1920, tag: 'TikTok' },
  { id: 'tiktok-landscape', label: '1920×1080 — TikTok Landscape', width: 1920, height: 1080, tag: 'TikTok' },
  { id: '4:3-1080', label: '1440×1080 — 4:3 Legacy', width: 1440, height: 1080, tag: '4:3' },
  { id: '21:9-1080', label: '2560×1080 — Ultrawide', width: 2560, height: 1080, tag: 'Ultra' },
  { id: '21:9-1440', label: '3440×1440 — UW QHD', width: 3440, height: 1440, tag: 'Ultra' },
  { id: '1:1-1080', label: '1080×1080 — Square', width: 1080, height: 1080, tag: 'Square' },
  { id: '9:16-1080', label: '1080×1920 — Vertical 9:16', width: 1080, height: 1920, tag: 'Vertical' },
  { id: 'shorts', label: '1080×1920 — YouTube Shorts', width: 1080, height: 1920, tag: 'Shorts' },
  { id: 'insta-reel', label: '1080×1920 — Instagram Reel', width: 1080, height: 1920, tag: 'Reel' },
];

export interface HorrorSound {
  id: string;
  name: string;
  category: 'ambient' | 'effect' | 'music' | 'voice';
  description: string;
  file?: string;
}

export const HORROR_SOUNDS: HorrorSound[] = [
  // ── AMBIENT ──
  { id: 'deep-drone', name: 'Deep Drone', category: 'ambient', description: 'Low rumbling subsonic drone' },
  { id: 'wind-howl', name: 'Wind Howl', category: 'ambient', description: 'Haunted howling wind' },
  { id: 'thunder-rumble', name: 'Thunder Rumble', category: 'ambient', description: 'Distant rolling thunder' },
  { id: 'haunted-room', name: 'Haunted Room', category: 'ambient', description: 'Creaking haunted house' },
  { id: 'inferno', name: 'Hellfire Crackle', category: 'ambient', description: 'Roaring hellfire flames' },
  { id: 'void-hum', name: 'Void Hum', category: 'ambient', description: 'Infinite void resonance' },
  { id: 'ritual-chant', name: 'Ritual Chant', category: 'ambient', description: 'Demonic ritual chanting drone' },
  { id: 'static-loop', name: 'TV Static Loop', category: 'ambient', description: 'Endless TV static noise' },
  { id: 'heavy-rain', name: 'Heavy Rain', category: 'ambient', description: 'Torrential horror rain storm' },
  { id: 'thunderstorm', name: 'Thunderstorm', category: 'ambient', description: 'Full thunderstorm with rain' },
  // MP3 Ambient files
  { id: 'mp3-horror-ambience-01', name: 'Horror Ambience 01', category: 'ambient', description: 'Dark horror atmosphere', file: '/sounds/freesound_community-horror-ambience-01-66708.mp3' },
  { id: 'mp3-horror-bg-026', name: 'Horror Background 026', category: 'ambient', description: 'Suspense background atmosphere', file: '/sounds/universfield-horror-background-atmosphere-026-30-352879.mp3' },
  { id: 'mp3-horror-bg-06', name: 'Horror Background 06', category: 'ambient', description: 'Eerie background atmosphere', file: '/sounds/universfield-horror-background-atmosphere-06-199279.mp3' },
  { id: 'mp3-horror-bg-08', name: 'Horror Background 08', category: 'ambient', description: 'Dark background atmosphere', file: '/sounds/universfield-horror-background-atmosphere-08-215794.mp3' },
  { id: 'mp3-horror-bg-09', name: 'Horror Background 09', category: 'ambient', description: 'Horror background 09', file: '/sounds/universfield-horror-background-atmosphere-09-219111.mp3' },
  { id: 'mp3-horror-bg-main', name: 'Horror Atmosphere', category: 'ambient', description: 'Main horror atmosphere', file: '/sounds/universfield-horror-background-atmosphere-156462.mp3' },
  { id: 'mp3-horror-suspense', name: 'Horror Suspense BG', category: 'ambient', description: 'Suspense horror background', file: '/sounds/universfield-horror-background-atmosphere-for-suspense-166944.mp3' },
  { id: 'mp3-scary-atmosphere', name: 'Scary Atmosphere', category: 'ambient', description: 'Scary horror atmosphere', file: '/sounds/universfield-scary-horror-atmosphere-176754.mp3' },
  { id: 'mp3-dark-soundscape', name: 'Dark Soundscape', category: 'ambient', description: 'Dark horror soundscape', file: '/sounds/universfield-dark-horror-soundscape-345814.mp3' },
  { id: 'mp3-dark-suspense-30s', name: 'Dark Suspense 30s', category: 'ambient', description: 'Dark horror suspense 30s', file: '/sounds/universfield-dark-horror-suspense-30s-355836.mp3' },
  { id: 'mp3-tense-paranormal', name: 'Tense Paranormal', category: 'ambient', description: 'Tense paranormal horror', file: '/sounds/universfield-tense-paranormal-horror-15s-498138.mp3' },
  { id: 'mp3-tense-cinematic', name: 'Tense Cinematic', category: 'ambient', description: 'Cinematic paranormal horror', file: '/sounds/universfield-tense-paranormal-horror-cinematic-15s-498207.mp3' },
  { id: 'mp3-ghosts-on-film', name: 'Ghosts on Film', category: 'ambient', description: 'Ghost film atmosphere', file: '/sounds/universfield-ghosts-on-film-185898.mp3' },
  { id: 'mp3-horror-bg-atm', name: 'Horror Background Atm', category: 'ambient', description: 'Joris horror background', file: '/sounds/jorisvermeer-horror-background-atmosphere-030-394196.mp3' },
  { id: 'mp3-horror-suspense2', name: 'Horror Suspense', category: 'ambient', description: 'Uttam horror suspense', file: '/sounds/uttamkumar_r-horror-suspense-189369.mp3' },
  { id: 'mp3-horror-rumble-winds', name: 'Horror Rumble Winds', category: 'ambient', description: 'Rumbling horror winds', file: '/sounds/soundreality-horror-rumble-winds-253834.mp3' },
  { id: 'mp3-horror-pad-crowd', name: 'Horror Pad Crowd', category: 'ambient', description: 'Horror pad pitch crowd', file: '/sounds/soundreality-horror-pad-pitch-crowd-391598.mp3' },
  { id: 'mp3-flesh-horror', name: 'Flesh Growing Horror', category: 'ambient', description: 'Flesh growing horror sound', file: '/sounds/tanweraman-flesh-growing-horror-392360.mp3' },

  // ── EFFECTS ──
  { id: 'heartbeat', name: 'Heartbeat', category: 'effect', description: 'Slow creepy heartbeat' },
  { id: 'door-creak', name: 'Door Creak', category: 'effect', description: 'Old door slowly creaking' },
  { id: 'chains', name: 'Chains Rattling', category: 'effect', description: 'Metal chains clanking' },
  { id: 'church-bell', name: 'Funeral Bell', category: 'effect', description: 'Slow tolling death bell' },
  { id: 'demon-roar', name: 'Demon Roar', category: 'effect', description: 'Full demon roar explosion' },
  { id: 'electric-zap', name: 'Electric Zap', category: 'effect', description: 'Electric shock zap burst' },
  { id: 'jumpscare-sting', name: 'Jumpscare Sting', category: 'effect', description: 'Hollywood jumpscare hit' },
  { id: 'evil-laugh-sfx', name: 'Evil Laugh SFX', category: 'effect', description: 'Short evil laugh burst' },
  { id: 'death-rattle', name: 'Death Rattle', category: 'effect', description: 'Final death rattle breath' },
  // MP3 Effects
  { id: 'mp3-echo-jumpscare', name: 'Echo Jumpscare', category: 'effect', description: 'Echo jumpscare hit', file: '/sounds/freesound_community-echo-jumpscare-80933.mp3' },
  { id: 'mp3-echoed-screams', name: 'Echoed Screams', category: 'effect', description: 'Multiple echoed screams', file: '/sounds/freesound_community-echoed-screams-103515.mp3' },
  { id: 'mp3-monster-roar', name: 'Monster Roar', category: 'effect', description: 'Full monster roar', file: '/sounds/freesound_community-monster-roar-02-102957.mp3' },
  { id: 'mp3-monster-growls', name: 'Monster Growls', category: 'effect', description: 'Deep monster growls', file: '/sounds/freesound_community-monster-growls-70784.mp3' },
  { id: 'mp3-demonic-roar', name: 'Demonic Roar', category: 'effect', description: 'Full demonic roar', file: '/sounds/freesound_community-demonic-roar-40349.mp3' },
  { id: 'mp3-demon-haunting', name: 'Demon Haunting', category: 'effect', description: 'Scary demon haunting', file: '/sounds/freesound_community-033203_scary-demon-haunting-sound-76189.mp3' },
  { id: 'mp3-demon-growl-halloween', name: 'Demon Growl Halloween', category: 'effect', description: 'Halloween demon growl', file: '/sounds/freesound_community-demon-growl-for-halloween-spooky-creepy-scary-monster-ghoul-ghost-sounds-100123.mp3' },
  { id: 'mp3-mocking-demon', name: 'Mocking Demon Laugh', category: 'effect', description: 'Demon laughing growl', file: '/sounds/freesound_community-mocking-demon-laugh-growl-86811.mp3' },
  { id: 'mp3-horror-hit', name: 'Horror Hit Logo', category: 'effect', description: 'Horror hit logo sting', file: '/sounds/alex_kizenkov-horror-hit-logo-142395.mp3' },
  { id: 'mp3-braam-dark', name: 'Braam Dark Impact', category: 'effect', description: 'Biodynamic dark braam', file: '/sounds/bryansantosbreton-biodynamic-impact-braam-tonal-dark-176441.mp3' },
  { id: 'mp3-horror-kick', name: 'Horror Kick', category: 'effect', description: 'Horror kick impact', file: '/sounds/soundreality-horror-kick-247743.mp3' },
  { id: 'mp3-horror-temptation', name: 'Horror Temptation', category: 'effect', description: 'Horror temptation sting', file: '/sounds/soundreality-horror-temptation-249034.mp3' },
  { id: 'mp3-horror-action', name: 'Horror Thriller Action', category: 'effect', description: 'Horror thriller action', file: '/sounds/soundreality-horror-thriller-action-247745.mp3' },
  { id: 'mp3-dinosaur-growls', name: 'Dinosaur Growls', category: 'effect', description: 'Massive dinosaur growls', file: '/sounds/gsmsea-dinosaur-growls-431298.mp3' },
  { id: 'mp3-shark-scream', name: 'Shark Terror Scream', category: 'effect', description: 'Shark eerie scream', file: '/sounds/gsmsea-shark-eerie-scream-terrifying-growling-and-screaming-17-433581.mp3' },
  { id: 'mp3-monster-noise', name: 'Monster Noise', category: 'effect', description: 'Deep monster noise', file: '/sounds/alex_jauk-monster-noise-256448.mp3' },
  { id: 'mp3-monstrous-scream', name: 'Monstrous Scream', category: 'effect', description: 'Full monstrous scream', file: '/sounds/alex_jauk-monstrous-scream-187949.mp3' },
  { id: 'mp3-creepy-growling', name: 'Creepy Growling', category: 'effect', description: 'Creepy monster growling', file: '/sounds/dragon-studio-creepy-growling-sfx-472368.mp3' },
  { id: 'mp3-creepy-monster-growl', name: 'Creepy Monster Growl', category: 'effect', description: 'Creepy monster growl', file: '/sounds/dragon-studio-creepy-monster-growling-472378.mp3' },
  { id: 'mp3-deep-guttural', name: 'Deep Guttural Growl', category: 'effect', description: 'Deep guttural growl', file: '/sounds/dragon-studio-deep-guttural-growl-472380.mp3' },
  { id: 'mp3-beast-growl', name: 'Beast Growl', category: 'effect', description: 'Growl of the beast', file: '/sounds/dragon-studio-growl-of-the-beast-504021.mp3' },
  { id: 'mp3-monster-growl', name: 'Monster Growl', category: 'effect', description: 'Monster growl sound', file: '/sounds/dragon-studio-monster-growl-390285.mp3' },
  { id: 'mp3-t-rex-growl', name: 'T-Rex Growl', category: 'effect', description: 'T-Rex dinosaur growl', file: '/sounds/dragon-studio-t-rex-growl-324746.mp3' },
  { id: 'mp3-werewolf-growl', name: 'Werewolf Growl', category: 'effect', description: 'Werewolf monster growl', file: '/sounds/dragon-studio-werewolf-growl-511303.mp3' },
  { id: 'mp3-thunder-dragon', name: 'Thunder Dragon Roar', category: 'effect', description: 'Thunder dragon voice roar', file: '/sounds/phatphrogstudio-thunder-dragon-voice-roar-478143.mp3' },
  { id: 'mp3-dragon-growl', name: 'Dragon Growl', category: 'effect', description: 'Dragon voice growl', file: '/sounds/phatphrogstudio-dragon-voice-growl-496281.mp3' },
  { id: 'mp3-evil-roar', name: 'Evil Roar', category: 'effect', description: 'Kunal evil roar', file: '/sounds/kunal_acharjee-evil-roar-271402.mp3' },
  { id: 'mp3-distorted-demon', name: 'Distorted Demon Growl', category: 'effect', description: 'Distorted demon growl', file: '/sounds/u_fn3kboel2x-distorted-demon-growl-203455.mp3' },
  { id: 'mp3-distant-demonic', name: 'Distant Demonic Scream', category: 'effect', description: 'Distant demonic scream', file: '/sounds/u_503t47r0fo-distant-demonic-scream-and-debris-346596.mp3' },
  { id: 'mp3-alien-noise', name: 'Alien Noise Scream', category: 'effect', description: 'Alien noise person screaming', file: '/sounds/flutie8211-low-pitch-alien-noise-person-screaming-499466.mp3' },
  { id: 'mp3-dark-horror-opener', name: 'Dark Horror Opener', category: 'effect', description: 'Dark horror opener sting', file: '/sounds/simplesound-dark-horror-opener-443328.mp3' },

  // ── MUSIC ──
  { id: 'dark-piano', name: 'Dark Piano Melody', category: 'music', description: 'Haunting minor key piano' },
  { id: 'horror-strings', name: 'Horror Strings', category: 'music', description: 'Tense orchestral strings' },
  { id: 'music-box', name: 'Broken Music Box', category: 'music', description: 'Warped music box tune' },
  { id: 'organ-drone', name: 'Gothic Organ', category: 'music', description: 'Dark cathedral organ drone' },
  { id: 'violin-shriek', name: 'Violin Shriek', category: 'music', description: 'Screeching horror violin' },
  { id: 'choir-dark', name: 'Dark Choir', category: 'music', description: 'Demonic choral voices' },
  { id: 'synth-horror', name: 'Synth Horror', category: 'music', description: '80s horror synth atmosphere' },
  // MP3 Music
  { id: 'mp3-horror-piano', name: 'Horror Piano', category: 'music', description: 'Simple horror piano', file: '/sounds/simplesound-horror-piano-443326.mp3' },
  { id: 'mp3-horror-trailer', name: 'Horror Trailer', category: 'music', description: 'Horror trailer music', file: '/sounds/simplesound-horror-trailer-443327.mp3' },
  { id: 'mp3-intense-horror', name: 'Intense Horror Music', category: 'music', description: 'Intense horror music 01', file: '/sounds/freesound_community-intense-horror-music-01-14890.mp3' },
  { id: 'mp3-scary-music-box', name: 'Scary Music Box', category: 'music', description: 'Scary music box melody', file: '/sounds/universfield-scary-music-box-165983.mp3' },
  { id: 'mp3-cosmic-oblivion', name: 'Cosmic Oblivion', category: 'music', description: 'Neon nexus cosmic music', file: '/sounds/phatphrogstudio-cosmic-oblivion-neon-nexus-477911.mp3' },
  { id: 'mp3-cyber-attack', name: 'Cyber Attack', category: 'music', description: 'Datastorm rebellion music', file: '/sounds/phatphrogstudio-cyber-attack-datastorm-rebellion-477469.mp3' },
  { id: 'mp3-infinite-expanse', name: 'Infinite Expanse', category: 'music', description: 'Piano nova trails music', file: '/sounds/phatphrogstudio-infinite-expanse-piano-nova-trails-477471.mp3' },
  { id: 'mp3-internal-fury', name: 'Internal Fury', category: 'music', description: 'Fury dance horror music', file: '/sounds/phatphrogstudio-internal-fury-furyx27s-dance-477470.mp3' },
  { id: 'mp3-plagued-bastion', name: 'Plagued Bastion', category: 'music', description: 'Survival undead haven', file: '/sounds/phatphrogstudio-plagued-bastion-survival-undead-haven-477915.mp3' },
  { id: 'mp3-pyro-witch', name: 'Pyro Witch', category: 'music', description: 'Fireborn saga action music', file: '/sounds/phatphrogstudio-pyro-witch-fireborn-saga-royalty-free-action-music-502322.mp3' },
  { id: 'mp3-samurai-spirit', name: 'Samurai Spirit', category: 'music', description: 'Cursed oni EDM music', file: '/sounds/phatphrogstudio-samurai-spirit-cursed-oni-edm-royalty-free-music-502868.mp3' },
  { id: 'mp3-creaking-cradle', name: 'Creaking Cradle', category: 'music', description: 'Nameless flesh music', file: '/sounds/phatphrogstudio-creaking-cradle-nameless-flesh-477965.mp3' },
  { id: 'mp3-horror-voice-flashbacks', name: 'Horror Voice Flashbacks', category: 'music', description: 'Horror voice flashback music', file: '/sounds/freesound_community-horror-voice-flashbacks-14469.mp3' },
  { id: 'mp3-screams-agony', name: 'Screams of Agony', category: 'music', description: 'Screams of agony track', file: '/sounds/soundreality-screams-of-agony-142447.mp3' },

  // ── VOICES & SCREAMS ──
  { id: 'scream', name: 'Terror Scream', category: 'voice', description: 'Blood-curdling scream' },
  { id: 'scream-female', name: 'Female Horror Scream', category: 'voice', description: 'Hollywood female scream' },
  { id: 'growl', name: 'Demonic Growl', category: 'voice', description: 'Deep demonic growl' },
  { id: 'laugh', name: 'Maniacal Laugh', category: 'voice', description: 'Evil maniacal laughter' },
  { id: 'crying', name: 'Ghost Crying', category: 'voice', description: 'Mournful ghost sobbing' },
  { id: 'whisper', name: 'Demonic Whisper', category: 'voice', description: 'Close demonic whisper' },
  { id: 'breathing', name: 'Heavy Breathing', category: 'voice', description: 'Ragged heavy breathing' },
  { id: 'moan', name: 'Death Moan', category: 'voice', description: 'Low death moan groan' },
  { id: 'child-laugh', name: 'Ghost Child Laugh', category: 'voice', description: 'Creepy child laughter' },
  { id: 'wail', name: 'Banshee Wail', category: 'voice', description: 'Piercing banshee wail' },
  { id: 'possessed-scream', name: 'Possessed Scream', category: 'voice', description: 'Exorcism possession scream' },
  { id: 'death-scream', name: 'Death Scream', category: 'voice', description: 'Final death agony scream' },
  // MP3 Voices & Screams
  { id: 'mp3-demonic-woman-scream', name: 'Demonic Woman Scream', category: 'voice', description: 'Demonic woman scream', file: '/sounds/freesound_community-demonic-woman-scream-6333.mp3' },
  { id: 'mp3-evil-shriek', name: 'Evil Shriek', category: 'voice', description: 'Evil high shriek', file: '/sounds/freesound_community-evil-shreik-45560.mp3' },
  { id: 'mp3-forest-monster', name: 'Forest Monster Scream', category: 'voice', description: 'Forest monster scream', file: '/sounds/freesound_community-forest-monster-scream1-104247.mp3' },
  { id: 'mp3-ghastly-groan', name: 'Ghastly Groan', category: 'voice', description: 'Ghastly groaning sound', file: '/sounds/freesound_community-ghastly-groan-48064.mp3' },
  { id: 'mp3-girl-scream-1', name: 'Girl Scream 1', category: 'voice', description: 'Girl horror scream', file: '/sounds/freesound_community-girl-scream-45657.mp3' },
  { id: 'mp3-girl-scream-2', name: 'Girl Scream 2', category: 'voice', description: 'Girl horror scream 2', file: '/sounds/freesound_community-girl-scream-83987.mp3' },
  { id: 'mp3-monster-screech', name: 'Monster Screech', category: 'voice', description: 'High quality monster screech', file: '/sounds/freesound_community-high-quality-monster-screech-65012.mp3' },
  { id: 'mp3-little-girl-scream', name: 'Little Girl Scream', category: 'voice', description: 'Little girl screaming', file: '/sounds/freesound_community-little-girl-screaming-101185.mp3' },
  { id: 'mp3-young-girl-scream', name: 'Young Girl Scream', category: 'voice', description: 'Young girl scream', file: '/sounds/freesound_community-young-girl-screaming-1-90519.mp3' },
  { id: 'mp3-multiple-screams', name: 'Multiple Female Screams', category: 'voice', description: 'Multiple female screams', file: '/sounds/freesound_community-multiple-female-screams-70786.mp3' },
  { id: 'mp3-scary-scream', name: 'Scary Scream', category: 'voice', description: 'Scary scream burst', file: '/sounds/freesound_community-scary-scream-3-81274.mp3' },
  { id: 'mp3-scream-1', name: 'Scream 1', category: 'voice', description: 'Pure scream sound', file: '/sounds/freesound_community-scream-85218.mp3' },
  { id: 'mp3-scream-2', name: 'Scream 2', category: 'voice', description: 'Scream 2 sound', file: '/sounds/freesound_community-scream-90747.mp3' },
  { id: 'mp3-scream-echo', name: 'Scream With Echo', category: 'voice', description: 'Echoing scream', file: '/sounds/freesound_community-scream-with-echo-46585.mp3' },
  { id: 'mp3-terrifying-scream', name: 'Terrifying Scream', category: 'voice', description: 'Most terrifying scream', file: '/sounds/freesound_community-terrifying-scream-32389.mp3' },
  { id: 'mp3-very-intense-hell', name: 'Very Intense Hell', category: 'voice', description: 'Intense hell screaming', file: '/sounds/freesound_community-very-intense-hell-72137.mp3' },
  { id: 'mp3-whispers-screams', name: 'Whispers & Screams', category: 'voice', description: 'Whispers and screams mix', file: '/sounds/freesound_community-whispers-and-screams-87177.mp3' },
  { id: 'mp3-zombie-growl', name: 'Zombie Growl', category: 'voice', description: 'Zombie growl sound', file: '/sounds/freesound_community-zombie-growl-3-6863.mp3' },
  { id: 'mp3-zombie-pain', name: 'Zombie Pain', category: 'voice', description: 'Zombie pain moan', file: '/sounds/freesound_community-zombie-pain-1-95166.mp3' },
  { id: 'mp3-zombie-roar', name: 'Zombie Roar', category: 'voice', description: 'Zombie roar sound', file: '/sounds/freesound_community-zombie-roar-104542.mp3' },
  { id: 'mp3-zombie-scream', name: 'Zombie Scream', category: 'voice', description: 'Monster zombie scream', file: '/sounds/freesound_community-monster-zombie-scream-105972.mp3' },
  { id: 'mp3-female-zombie', name: 'Female Zombie Screams', category: 'voice', description: 'Female zombie screams', file: '/sounds/dragon-studio-female-zombie-screams-324744.mp3' },
  { id: 'mp3-woman-screaming', name: 'Woman Screaming', category: 'voice', description: 'Woman screaming SFX', file: '/sounds/dragon-studio-woman-screaming-sfx-screaming-sound-effect-320169.mp3' },
  { id: 'mp3-zombie-screech', name: 'Zombie Screech', category: 'voice', description: 'Zombie screech sound', file: '/sounds/dragon-studio-zombie-screech-sound-effect-312865.mp3' },
  { id: 'mp3-scary-scream-female', name: 'Scary Woman Scream', category: 'voice', description: 'Ultra realistic woman scream', file: '/sounds/virtual_vibes-scary-woman-scream-ultra-realistic-379378.mp3' },
  { id: 'mp3-woman-scream-hd', name: 'Woman Scream HD', category: 'voice', description: 'HD woman scream', file: '/sounds/virtual_vibes-woman-scream-sound-hd-379381.mp3' },
  { id: 'mp3-female-screaming', name: 'Female Screaming HD', category: 'voice', description: 'Female screaming audio HD', file: '/sounds/virtual_vibes-female-screaming-audio-hd-379382.mp3' },
  { id: 'mp3-angry-man-yell', name: 'Angry Man Yell', category: 'voice', description: 'Angry man yell HD', file: '/sounds/virtual_vibes-angry-man-yell-sound-hd-379386.mp3' },
  { id: 'mp3-frantic-scream', name: 'Frantic Screaming', category: 'voice', description: 'Frantic non-stop screaming', file: '/sounds/phobiix-frantic-screaming-213549.mp3' },
  { id: 'mp3-scared-woman', name: 'Scared Woman Scream', category: 'voice', description: 'Halloween scared woman', file: '/sounds/scottishperson-sound-effect-halloween-scared-woman-scream-01-253233.mp3' },
  { id: 'mp3-male-death-scream', name: 'Male Death Scream', category: 'voice', description: 'Male death scream horror', file: '/sounds/universfield-male-death-scream-horror-352706.mp3' },
  { id: 'mp3-man-scream', name: 'Man Scream', category: 'voice', description: 'Man scream 08', file: '/sounds/universfield-man-scream-08-352438.mp3' },
  { id: 'mp3-demon-voice', name: 'Demon Voice', category: 'voice', description: 'Haunted demon voice', file: '/sounds/hauntedhouseentertainment-demon-voice-246555.mp3' },
  { id: 'mp3-demon-chanting', name: 'Demon Spirit Chanting', category: 'voice', description: 'Demon spirit angry chanting', file: '/sounds/phatphrogstudio-demon-spirit-angry-chanting-no-ai-479754.mp3' },
  { id: 'mp3-demon-whispers', name: 'Demon Spirit Whispers', category: 'voice', description: 'Demon ghost whispers muttering', file: '/sounds/phatphrogstudio-demon-spirit-voice-ghost-whispers-amp-muttering-496706.mp3' },
  { id: 'mp3-demon-die', name: 'Demon Voice: Die', category: 'voice', description: 'Demon voice saying die', file: '/sounds/phatphrogstudio-demon-voice-die-488316.mp3' },
  { id: 'mp3-demon-growling', name: 'Demon Voice Growling', category: 'voice', description: 'Demon voice growling', file: '/sounds/phatphrogstudio-demon-voice-growling-503874.mp3' },
  { id: 'mp3-demon-no-mercy', name: 'Demon: No Mercy', category: 'voice', description: 'Demon voice no mercy', file: '/sounds/phatphrogstudio-demon-voice-no-mercy-477827.mp3' },
  { id: 'mp3-demon-no-running', name: 'Demon: No More Running', category: 'voice', description: 'Demon no more running', file: '/sounds/phatphrogstudio-demon-voice-no-more-running-480562.mp3' },
  { id: 'mp3-demon-smell-flesh', name: 'Demon: Smell Flesh', category: 'voice', description: 'Demon smells flesh', file: '/sounds/phatphrogstudio-demon-voice-smell-flesh-no-ai-479322.mp3' },
  { id: 'mp3-evil-doll-laugh', name: 'Evil Doll Laugh', category: 'voice', description: 'Evil doll creepy laugh', file: '/sounds/phatphrogstudio-evil-doll-voice-creepy-laugh-477944.mp3' },
  { id: 'mp3-lich-come-closer', name: 'Lich: Come Closer', category: 'voice', description: 'Lich demon come closer', file: '/sounds/phatphrogstudio-lich-demonic-voice-come-closer-502312.mp3' },
  { id: 'mp3-lich-i-sense-you', name: 'Lich: I Sense You', category: 'voice', description: 'Lich demon I sense you', file: '/sounds/phatphrogstudio-lich-demonic-voice-i-sense-you-490452.mp3' },
  { id: 'mp3-oni-laugh-1', name: 'Oni Demon Laugh', category: 'voice', description: 'Oni demon laughter', file: '/sounds/phatphrogstudio-oni-demon-voice-demonic-laughter-477923.mp3' },
  { id: 'mp3-oni-laugh-2', name: 'Oni Demon Laugh 2', category: 'voice', description: 'Oni demon laughter 2', file: '/sounds/phatphrogstudio-oni-demon-voice-demonic-laughter-2-no-ai-479320.mp3' },
  { id: 'mp3-oni-laugh-3', name: 'Oni Demon Laugh 3', category: 'voice', description: 'Oni demon laughter 3', file: '/sounds/phatphrogstudio-oni-demon-voice-demonic-laughter-3-488654.mp3' },
  { id: 'mp3-zombie-moans', name: 'Zombie Idle Moans', category: 'voice', description: 'Zombie idle moaning', file: '/sounds/phatphrogstudio-zombie-voice-idle-moans-2-no-ai-479321.mp3' },
  { id: 'mp3-snarls-growls', name: 'Snarls & Growls', category: 'voice', description: 'Snarls and growls mix', file: '/sounds/voicebosch-snarls-and-growls-172823.mp3' },
  { id: 'mp3-monster-moan', name: 'Monster Moan & Squeel', category: 'voice', description: 'Monster moan and squeel', file: '/sounds/wikitwonkaweckords_llc-monster-moan-and-squeel-146632.mp3' },
  { id: 'mp3-nazgul', name: 'Nazgul Screech', category: 'voice', description: 'Nazgul with low bass', file: '/sounds/freesound_community-nazgul-w-low-bass-37269.mp3' },
  { id: 'mp3-horror-sound-lurking', name: 'Lurking Horror', category: 'voice', description: 'Lurking horror monster sound', file: '/sounds/alesiadavina-horror-sound-lurking-horror-monster-189948.mp3' },
  { id: 'mp3-scary-horror-sound', name: 'Scary Horror Sound', category: 'voice', description: 'Scary horror sound', file: '/sounds/alesiadavina-scary-horror-sound-189949.mp3' },
  { id: 'mp3-scream-sfx-1', name: 'Scream SFX 1', category: 'voice', description: 'Horror scream SFX', file: '/sounds/jusatti890-scream-horror-sfx-490899.mp3' },
  { id: 'mp3-scream-sfx-2', name: 'Scream SFX 2', category: 'voice', description: 'Horror scream SFX 2', file: '/sounds/jusatti890-scream-horror-sfx-490908.mp3' },
  { id: 'mp3-scream-sfx-3', name: 'Scream SFX 3', category: 'voice', description: 'Horror scream SFX 3', file: '/sounds/jusatti890-scream-horror-sfx-490909.mp3' },
  { id: 'mp3-scream-sfx-4', name: 'Scream SFX 4', category: 'voice', description: 'Horror scream SFX 4', file: '/sounds/jusatti890-scream-horror-sfx-490910.mp3' },
  { id: 'mp3-scream-sfx-5', name: 'Scream SFX 5', category: 'voice', description: 'Horror scream SFX 5', file: '/sounds/jusatti890-scream-horror-sfx-490916.mp3' },
  { id: 'mp3-demon-missed', name: 'Demon: Missed', category: 'voice', description: 'Demon voice missed', file: '/sounds/phatphrogstudio-demon-voice-missed-477829.mp3' },
  { id: 'mp3-defeat-outros', name: 'Defeat Outros', category: 'voice', description: 'Defeat outros game sounds', file: '/sounds/phatphrogstudio-defeat-outros-game-sounds-collection-477823.mp3' },
  { id: 'mp3-access-granted', name: 'Access Granted', category: 'voice', description: 'Android voice access granted', file: '/sounds/phatphrogstudio-android-voice-access-granted-477825.mp3' },
  { id: 'mp3-free-demon-ghost', name: 'Free Demon Ghost', category: 'voice', description: 'Free demon ghost sounds', file: '/sounds/freesound_community-free-demon-ghost-sounds-27789.mp3' },
];

export interface ParticleEffect {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const PARTICLE_EFFECTS: ParticleEffect[] = [
  { id: 'blood-drip', name: 'Blood Dripping', description: 'Blood drips from top', icon: '🩸' },
  { id: 'fire-flakes', name: 'Fire Embers', description: 'Rising fire ember flakes', icon: '🔥' },
  { id: 'ashes', name: 'Falling Ashes', description: 'Dark ash particles fall', icon: '💀' },
  { id: 'fog', name: 'Creeping Fog', description: 'Ground fog wisps', icon: '🌫️' },
  { id: 'sparks', name: 'Evil Sparks', description: 'Red spark bursts', icon: '⚡' },
  { id: 'skulls', name: 'Floating Skulls', description: 'Small skulls float up', icon: '💀' },
  { id: 'tears', name: 'Dark Tears', description: 'Dark tear drops fall', icon: '😭' },
  { id: 'lightning', name: 'Lightning Flashes', description: 'Background lightning', icon: '🌩️' },
];

export interface UploadedImage {
  id: string;
  file: File;
  url: string;
  name: string;
  animation: string | null;
  animations?: string[];
  greenScreen: boolean;
  position: { x: number; y: number };
  scale: number;
  rotation: number;
  opacity: number;
}

export type AnimationMode = 'single' | 'slideshow' | 'all-visible' | 'random-appear';
